version: 2

models:
  - name: daily_conditions
    columns:
      - name: waypoint_name
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: elevation
        tests:
          - not_null

  - name: elevation_gradient
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [waypoint_name, date]
    columns:
      - name: waypoint_name
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: elevation
        tests:
          - not_null

  - name: summit_window
    columns:
      - name: date
        tests:
          - not_null
          - unique
      - name: is_viable
        tests:
          - not_null
      - name: is_recommended
        tests:
          - not_null
      - name: is_ideal
        tests:
          - not_null
      - name: overall_score
        tests:
          - not_null
